### PR TITLE
fix for rendering enviroment variables for docker compose

### PR DESCRIPTION
**Pull request by StevusPrimus**
This improves the way the config can be passed via docker compose.

### CODE REVIEW

**Comment by LaurenceJJones** [comment]
Currently this will break all known Kubernetes deployments as the `BOUNCER_CONFIG` is currently used to update the environment to point towards a new file.

**Comment by StevusPrimus** [comment]
Sure will check this!

**Comment by StevusPrimus** [comment]
@LaurenceJJones do you think it is maybe better to just add all single missing parameters to the `docker-start.sh`, instead of using a multiline env variable? I think that's more according to standard right?

**Comment by StevusPrimus** [comment]
All done. Depending on https://github.com/crowdsecurity/lua-cs-bouncer/pull/75

**Review by he2ss — APPROVED** [review]

**Pull request merged**
